# Generated by Django 2.1.7 on 2019-02-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, verbose_name='产品编号')),
                ('barcode', models.CharField(max_length=10, verbose_name='条形码')),
                ('product_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('vintage', models.IntegerField(verbose_name='产品年份')),
                ('variety', models.CharField(max_length=20, null=True, verbose_name='葡萄品种')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='葡萄产区')),
                ('pack_size', models.IntegerField(verbose_name='单箱数量')),
                ('inventory_in_box', models.IntegerField(verbose_name='当前库存（箱）')),
                ('inventory_in_bottle', models.IntegerField(verbose_name='当前库存（瓶）')),
            ],
        ),
    ]
