# Generated by Django 2.1.7 on 2019-02-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('sku', models.CharField(max_length=10, verbose_name='产品编号')),
                ('barcode', models.CharField(max_length=10, verbose_name='条形编码')),
                ('vintage', models.IntegerField(blank=True, null=True, verbose_name='产品年份')),
                ('variety', models.CharField(blank=True, max_length=20, null=True, verbose_name='葡萄品种')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='葡萄产区')),
                ('pack_size', models.IntegerField(null=True, verbose_name='单箱数量')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('contract_number', models.CharField(max_length=20, verbose_name='采购单号')),
            ],
            options={
                'verbose_name': '采购清单',
                'verbose_name_plural': '采购清单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='产品数量')),
                ('unit', models.CharField(choices=[('box', '箱'), ('bottle', '瓶')], default='box', max_length=10, verbose_name='数量单位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='采购产品')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseOrder', verbose_name='采购单号')),
            ],
            options={
                'verbose_name': '采购清单行',
                'verbose_name_plural': '采购清单行',
            },
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=20, verbose_name='顾客姓名')),
                ('location', models.CharField(blank=True, max_length=10, null=True, verbose_name='所在区域')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '采购商',
                'verbose_name_plural': '采购商',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Purchaser', verbose_name='采购商')),
            ],
            options={
                'verbose_name': '销售清单',
                'verbose_name_plural': '销售清单',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='产品数量')),
                ('unit', models.CharField(choices=[('box', '箱'), ('bottle', '瓶')], default='箱', max_length=10, verbose_name='数量单位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='销售产品')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SaleOrder', verbose_name='销售单号')),
            ],
            options={
                'verbose_name': '销售清单行',
                'verbose_name_plural': '销售清单行',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier', verbose_name='供货商'),
        ),
    ]
