# Generated by Django 2.1.7 on 2019-02-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('箱', 'box'), ('瓶', 'bottle')], default='box', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=10, verbose_name='条形编码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.IntegerField(null=True, verbose_name='单箱数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='葡萄品种'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vintage',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品年份'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier', verbose_name='采购商家'),
        ),
    ]
