# Generated by Django 2.1.7 on 2019-02-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190219_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contract_number',
            field=models.CharField(default=1, max_length=20, verbose_name='采购单号'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='采购产品'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseOrder', verbose_name='采购单号'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.IntegerField(verbose_name='产品数量'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.CharField(choices=[('箱', 'box'), ('瓶', 'bottle')], default='box', max_length=10, verbose_name='数量单位'),
        ),
    ]
