# Generated by Django 2.1.7 on 2019-02-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190219_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='contract_number',
            field=models.CharField(max_length=20, verbose_name='采购单号'),
        ),
    ]
