# Generated by Django 2.1.7 on 2019-02-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190219_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Purchaser', verbose_name='采购商')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='产品数量')),
                ('unit', models.CharField(choices=[('箱', 'box'), ('瓶', 'bottle')], default='box', max_length=10, verbose_name='数量单位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='销售产品')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SaleOrder', verbose_name='销售单号')),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier', verbose_name='供货商'),
        ),
    ]
