# Generated by Django 2.1.7 on 2019-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190219_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_in_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_in_bottle',
            field=models.IntegerField(verbose_name='散装库存'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_in_box',
            field=models.IntegerField(verbose_name='整箱库存'),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='purchaser_name',
            field=models.CharField(max_length=20, verbose_name='顾客姓名'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=20, verbose_name='公司名称'),
        ),
    ]
