# Generated by Django 2.1.7 on 2019-02-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190219_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_in_total',
            field=models.IntegerField(default=0, editable=False, verbose_name='总库存（瓶）'),
        ),
    ]
