# Generated by Django 2.1.7 on 2019-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190219_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品信息', 'verbose_name_plural': '产品信息'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': '采购清单', 'verbose_name_plural': '采购清单'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'verbose_name': '采购清单行', 'verbose_name_plural': '采购清单行'},
        ),
        migrations.AlterModelOptions(
            name='purchaser',
            options={'verbose_name': '采购商', 'verbose_name_plural': '采购商'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'verbose_name': '销售清单', 'verbose_name_plural': '销售清单'},
        ),
        migrations.AlterModelOptions(
            name='saleorderline',
            options={'verbose_name': '销售清单行', 'verbose_name_plural': '销售清单行'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.CharField(choices=[('box', '箱'), ('bottle', '瓶')], default='箱', max_length=10, verbose_name='数量单位'),
        ),
    ]
