# Generated by Django 2.1.7 on 2019-02-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190219_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_in_bottle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_in_box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_in_total',
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.CharField(choices=[('box', '箱'), ('bottle', '瓶')], default='box', max_length=10, verbose_name='数量单位'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='unit',
            field=models.CharField(choices=[('box', '箱'), ('bottle', '瓶')], default='箱', max_length=10, verbose_name='数量单位'),
        ),
    ]
